import { Entity, Column, PrimaryGeneratedColumn, ManyToOne } from "typeorm";
import { User } from "./user.entity";
import { ApiProperty } from "@nestjs/swagger";

@Entity()
export class Task {
    
    @ApiProperty({
        description: 'Unique identifier for the task. Automatically generated by the database.',
        example: '12',
    })
    @PrimaryGeneratedColumn()
    id: number;

    @ApiProperty({
        description: "The title of the task that describes its purpose.",
        example: "Implement user authentication"
    })
    @Column()
    title: string;

    @ApiProperty({
        description: "A detailed description of the task, outlining the requirements and goals.",
        example: "Create a secure authentication system using JWT tokens."
    })
    @Column({type: 'text'})
    description: string;

    @ApiProperty({
        description: "Indicates whether the task has been completed. Defaults to false if not provided.",
        example: false
    })
    @Column({default: false})
    completed: boolean;

    @ApiProperty({
        description: 'The user to whom the task is assigned. Represents a many-to-one relationship with the User entity.',
        type: () => User,
    })
    @ManyToOne(() => User, (user) => user.assignedTasks)
    user: User;

    @ApiProperty({
        description: 'The user who owns the task. Represents a many-to-one relationship with the User entity.',
        type: () => User,
    })
    @ManyToOne(() => User, (user) => user.ownedTask)
    owner: User;
}